### ISSUE TITLE
Objetivo do Produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T03-Paraizo#1]
Precisa rever o objetivo do produto. A equipe apresenta mais de um objetivo, a partir de diferentes perspectivas. Não há um objetivo único do produto.

"aprimorar o cadatro e consulta de dados dos pacientes"
"fornecer um local de compartilhamento"

Sugestão: criem um objetivo principal e alguns objetivos específicos.

**Comment by m4rllon** [comment]
O texto foi alterado de:

"
O objetivo do produto Paraizo é aprimorar o cadatro e consulta de dados dos pacientes, como dados técnicos (informações referêntes a seus disturbios e problemas físicos), histórico clínico, hábitos de vida, tratamentos realizados, uso de medicamentos e localizações de dores, substituindo processos manuais e informais, como registros em planilhas e locais temporários, que já não atendem às necessidades da organização por conta do tempo significativo que esse processo exige atualmente e também pela centralização deste trabalho em uma só funcionária.

Já ao olhar para as necessidades dos pacientes da clinica, o objetivo é fornecer um local de compartilhamento, acessado por meio de login, que reúna os resultados dos pacientes, facilitando a avaliação dos tratamentos realizados e o acompanhamento dos resultados por parte dos mesmos. Vale ressaltar que para isso o sistema deverá ser uma solução web com a capacidade de ser reproduzida em diferentes tamanhos de tela.

O produto também contará com uma landing page, que divulgará informações da clínica, como serviços, quadro de funcionários, avaliações e resultados, promovendo maior credibilidade a clínica no mercado, ao passo que auxiliará com a prospecção de novos clientes. Além disso, o sistema possibilitará o cadastro e a visualização de agendamentos de consultas, com integração ao Google Agenda, facilitando a gestão dos horários por parte da equipe da clínica.
"

Para:

"
O objetivo do produto Paraizo é viabilizar a ampliação da quantidade de clientes da clínica. Para isso, faz-se necessário a redução do tempo demandado na execução de atividades relacionadas à documentação e agendamento de consultas, possibilitando assim a realização dessas atividades com um número maior de clientes, e facilitar a divulgação e marketing do estabelecimento. Para tanto, este produto irá, por meio de uma única plataforma web:

Aprimorar o cadatro e consulta de dados dos pacientes, como dados técnicos (informações referêntes a seus disturbios e problemas físicos), histórico clínico, hábitos de vida, tratamentos realizados, uso de medicamentos e localizações de dores, substituindo processos manuais e informais, como registros em planilhas e locais temporários, que já não atendem às necessidades da organização por conta do tempo significativo que esse processo exige atualmente e também pela centralização deste trabalho em uma só funcionária.

Fornecer um local de compartilhamento, acessado por meio de login, que reúna os resultados dos pacientes, facilitando a avaliação dos tratamentos realizados e o acompanhamento dos resultados por parte dos mesmos. Vale ressaltar que para isso o sistema deverá ser uma solução web com a capacidade de ser reproduzida em diferentes tamanhos de tela.

Ter uma landing page, que divulgará informações da clínica, como serviços, quadro de funcionários, avaliações e resultados, promovendo maior credibilidade a clínica no mercado, ao passo que auxiliará com a prospecção de novos clientes.

Possibilitar o cadastro e a visualização de agendamentos de consultas, com integração ao Google Agenda, facilitando a gestão dos horários por parte da equipe da clínica.
"

**Comment by maykonjuso** [comment]
Correção revisada.
