### ISSUE TITLE
Estratégia de ESW - RAD-Dual Track Agile

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T03-Paraizo#4]
Ao proporem a utilização do Dual-Track Agile junto com o RAD, vocês estão falando de uma abordagem híbrida que combina características de dois processos.
Contudo, da maneira como está, não está correto, pois o Dual-Tracj Agile está todo dentro da fase de Desenvolvimento do RAD. vamos lá:

Fases do RAD: (1) Planejamento de Requisitos; (2) Design e Prototipagem; (3) Desenvolvimento; e (4) Entrega e Implantação
Fases do Dual-Track Agile: (a) Discovery; e (b) Delivery

As fases (1) e (2) do RAD, são similares / complementares a fase (a) do Dual-Track.
A fase (3) do RAD e similar / complementar a fase (b) do Dual-Track.

Neste sentido, o Dual-Track, não deveria estar todo dentro da fase de Desenvolvimento, do RAD.

Avaliem e ajustem.

**Comment by Erick-ems** [comment]
Após revisão e debate com os mebros da equipe, foi optado pela remoção do Dual-Track. Pois foi indentificado um aumento da complexidade do projeto sem necessiade. FIcando assim somente com o RAD e alterando o metodo de desenvolvimento para o 
KANBAN.

**Comment by Erick-ems** [comment]
Ajustado novamente
