### ISSUE TITLE
Composição da Equipe

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T03-Paraizo#5]
Na composição da equipe, nem todos estão como participantes das atividades de requisitos. Isso deve ser revisto, **todos** devem estar nessas atividades.

**Comment by m4rllon** [comment]
O quadro de composição da equipe foi atualizado, adicionando os integrantes às atividades de requitos

**Comment by maykonjuso** [comment]
Correção revisada.
